[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "distiller-cm5-python"
version = "0.1.0"
description = "python exe of distiller python client"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [
  "aiohttp>=3.12.14",
  "colorama>=0.4.6",
  "evdev>=1.9.2",
  "fastapi>=0.116.1",
  "faster-whisper>=1.1.1",
  "fastmcp>=2.10.6",
  "jinja2>=3.0.0",
  "lgpio==0.2.2",
  "llama-cpp-python>=0.3.2",
  "mcp<=1.12",
  "nest-asyncio>=1.6",
  "numba>=0.61.2",
  "numpy>=1.24.0",
  "opencv-python>=4.12",
  "pillow>=11.3",
  "psutil>=7",
  "pyaudio>=0.2.14",
  "pydantic>=2.11.7",
  "pyqt6<6.8",
  "pyserial>=3.5",
  "qasync>=0.27.1",
  "requests>=2.32.4",
  "sherpa-onnx>=1.12.6",
  "sounddevice>=0.5.2",
  "soundfile>=0.13.1",
  "spidev>=3.7",
  "tomli-w>=1.0.0",
  "typing-extensions>=4.14.1",
  "uvicorn>=0.35",
]

author = [
  { name = "PamirAI Incorporated", email = "founders@pamir.ai" },
]

[tool.ruff]
target-version = "py311"
line-length = 100

[tool.uv]
required-environments = [ "platform_machine == 'aarch64'" ]
index-url = "https://pypi.org/simple"
extra-index-url = [
  "https://abetlen.github.io/llama-cpp-python/whl/cpu",
]
